#!/usr/bin/env python

import os
import pdb

import click
import numpy as np
import pandas as pd
import scipy

from scilmm.Estimation.HE import HE
from scilmm.FileFormats import Population

@click.command()
@click.argument("ibd_path", type=click.Path(exists=True))
@click.argument("entries_path", type=click.Path(exists=True))
@click.argument("pheno_path", type=click.Path(exists=True))
@click.argument("cov_path", type=click.Path(exists=True))
@click.argument("output", type=click.Path(exists=True))
def fitModel(ibd_path, entries_path, pheno_path, cov_path, output):
    """ Fits the GLM

    Parameters
    ---------
        ibd_path : str
            Path to IBD file

        entries_path : str
            Path to entries file

        pheno_path : str
            Path phenotype file with IID column and phenotype column
            without headers

        cov_path : str
            Path to covariate file with headers. First column should be IID
            value with one column per covariate following

        output : str
            Output directory to write results to
    """
    population = Population(entries_path, pheno_path, cov_path, ibd_path)

    he_est = HE(population.phenotype, population.covariates, [population.ibd])

    print(he_est)

if __name__ == "__main__":
    fitModel()
